kind: Job
apiVersion: batch/v1
metadata:
  name: demo-job
  namespace: nginx
spec:
  completions: 1
  parallelism: 2
  template:
    metadata:
      name: job-pod
      labels:
        app: batch-task
    spec:
      containers:
      - name: job-container
        image: busybox:latest
        command: [ "sh", "-c", "echo Hello World && sleep 10" ]
      restartPolicy: Never
