kind: ReplicaSet
apiVersion: apps/v1
metadata:
  name: nginx-rset
  namespace: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx

  template:
    metadata:
      name: nginx-rset-pod
      labels:
        app: nginx
    spec:      
      containers:
      - name: nginx-container
        image: nginx:latest
        ports:
        - containerPort: 80
